#ifndef _LXS_CONFIG_H_
#define _LXS_CONFIG_H_

#define LXS_HAS_DEBUGGER 1

#define LXS_HAS_LCD 1

#if LXS_HAS_LCD
#define LXS_LCD_DEBUG 1
#endif

#define LXS_DEBUGPRINT 1

#define LXS_NOTE_VELOCITY_MAX 127
#define LXS_MAX_NOTES 256
#define LXS_NOTELIST_DEBUG 0

#define LXS_HAS_LEDSTRIP 1

#if LXS_HAS_LEDSTRIP
#define LXS_LED_CLOCKPIN 2
#define LXS_LED_DATAPIN 3
#define LXS_LED_COUNT 18
#define LXS_LED_BRIGHTNESS 10
#endif

#endif /* _LXS_CONFIG_H_ */